### ISSUE TITLE
Arc crashes on ESLint parse errors

### ISSUE THREAD

**Issue by michaelmwu** [pinterest/arcanist-linters#21]
ruleId comes out to be None for babel-eslint. I fixed by changing to `$offense['ruleId'] || 'unknown'`

https://github.com/pinterest/arcanist-linters/blob/24c6667187f941dbe39c38efd5961f0a09b17f1b/src/ESLintLinter.php#L166

**Comment by jparise** [comment]
Thanks, @michaelmwu! Would you mind submitting a Pull Request with your fix? Otherwise, I'll try to get to this myself some time soon.

**Comment by michaelmwu** [comment]
https://github.com/pinterest/arcanist-linters/pull/22

**Comment by jparise** [comment]
Thanks!
